---
title: "dinocystDB"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dinocystDB}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  engine.opts = list(bash = "-l")
)
```

```{r setupRMD}
#install.packages("here")
here::i_am("vignettes/dinocystDB.Rmd")
```

Setting-up a SQLite database for the IODP sample locations.

```{bash setupDB, eval = F}
sqlite3 
.open 'inst/extdata/transferice.sqlite' # open db
.nullvalue NULL
.headers on
.mode column
```

# Connect to database from R

```{r connect}
# install.packages("RSQLite")
# install.packages("DBI")
# path to db
dbpath <- fs::path_package(package = "transferice", "extdata", "transferice.sqlite")
con <- DBI::dbConnect(
  RSQLite::SQLite(), 
  dbpath 
  )
```

# Write tables to database

## Dinocyst count data

```{r count}
# install.packages("readxl") # reading excel
# install.packages("tibble") # tibble data structure
# install.packages("janitor") # cleaning variable names
# install.packages("dplyr") # data wrangling
# metadata
meta <- c("station", "depth", "weight", "lycopodium", "lyc_tab", "geometry", 
          "contributors", "longitude", "latitude", "dino_tot")

shts <- readxl::excel_sheets(here::here("data-raw/SurfaceDinos.xlsx"))

# read dinocyst data (Thole 2021)
dino_thole <- readxl::read_xlsx(
  here::here("data-raw/SurfaceDinos.xlsx"), 
  sheet = shts[1],
  # explicit type casting is important
  col_types = c("text", rep("numeric", 38))
) |> 
  # clean variable names
  janitor::clean_names() |> 
  tibble::add_column(contributors = "Thole et al 2022") |> 
  dplyr::select(-.data$non_quat_dinos)

# read dinocyst data (Marret 2019)
dino_marret <- readxl::read_xlsx(
  here::here("data-raw/SurfaceDinos.xlsx"), 
  sheet = shts[3],
  # explicit type casting is important
  col_types = c("text", "numeric", "numeric", "text", rep("numeric", 92))
)  |>  
  # clean variable names
  janitor::clean_names() |> 
  dplyr::select(-.data$dino_tot)

# combine both dinocyst count datasets
dino_all <- dplyr::bind_rows(dino_marret, dino_thole) |> 
  dplyr::mutate(sample_id = dplyr::row_number(), .before = "station")

# remove all NA rows
dino_all <- dplyr::filter(
  dino_all, 
  !dplyr::if_all(-dplyr::any_of(meta), ~is.na(.))
)

# extract dino count data
dino_cnt <- dplyr::select(dino_all, -dplyr::any_of(meta))
# extract dino names
dino_nms <- tibble::tibble(
  species = names(dino_cnt)[names(dino_cnt) != "sample_id"]
) |> 
  dplyr::mutate(taxon_id = dplyr::row_number(), .before = "species")

# nsb long format
dino_cnt <- tidyr::pivot_longer(
  dino_cnt, 
  -sample_id, 
  names_to = "taxon_id", 
  values_to = "taxon_abundance", 
  values_drop_na = TRUE
) |> 
  # code taxon id
  dplyr::mutate(
    taxon_id =  
      dplyr::recode(
        taxon_id, 
        !!!setNames(dino_nms$taxon_id, nm = dino_nms$species)
      )
  )

# to database (NSB neptune_sample_taxa)
DBI::dbWriteTable(con, "neptune_sample_taxa", dino_cnt, overwrite = TRUE)
```

# Locations

```{r locations}
# extract geographic information
dino_loc <- dplyr::select(dino_all, site = .data$station, .data$longitude, 
                          .data$latitude) |> 
  dplyr::distinct(.data$site, .keep_all = TRUE) |> 
  dplyr::mutate(hole_id = dplyr::row_number(), .before = "site")

# to database (NSB neptune_hole_summary)
DBI::dbWriteTable(con, "neptune_hole_summary", dino_loc, overwrite = TRUE)
```

# Sample metadata

```{r sample}
# sample metadata selected
dino_smp <- dplyr::select(
  dino_all, 
  dplyr::any_of(c("sample_id", meta[!meta %in% c("longitude", "latitude")]))
  ) |> 
  # code hole_id
  dplyr::mutate(
    hole_id =  
      dplyr::recode(
        .data$station, 
        !!!setNames(dino_loc$hole_id, nm = dino_loc$site)
        )
    ) |> dplyr::select(-.data$station) # drop station

dino_sty <- dplyr::distinct(dino_smp, source_citation = .data$contributors) |> 
  dplyr::mutate(dataset_id = dplyr::row_number(), .before = "source_citation") 

# lose contributors
dino_smp <-  dplyr::select(dino_smp, -.data$contributors)

# to database (NSB neptune_sample)
DBI::dbWriteTable(con, "neptune_sample", dino_smp, overwrite = TRUE)
```


# Study metadata

The original units used for reporting the dinocyst data.

```{r units, eval = FALSE}
# from pdf table Marret et al 2020 with Okular
dino_sty <- clipr::read_clip_tbl() |>  
  # clean variable names
  janitor::clean_names()

# add units Thole et al
dino_sty <- dplyr::add_row(dino_sty,
    location = "Southern hemisphere",
    available_data = "Raw Counts",
    references = "Thole et al 2022"
    )

# write table to DB
DBI::dbWriteTable(con, "dino_sty", dino_sty)
```

# Species list

```{r species}
# install.packages("stringr")

# read taxon list (Thole et al)
taxons_thole <- readxl::read_xlsx(
  here::here("data-raw/SurfaceDinos.xlsx"), 
  sheet = shts[4],
  col_names = c("x", "name", "abbrev", "other")
) 

# subspecies of Selenopemphix antarctica (manual) and clean names
taxons_thole <- dplyr::mutate(
  taxons_thole, 
  abbrev = tolower(gsub("[^[:alnum:]]+", "", .data$abbrev)),
  name = dplyr::if_else(.data$abbrev == "sant", "Selenopemphix antarctica sp1", .data$name),
  name = gsub("Cyst of ", "", .data$name)
) |> 
  dplyr::add_row(abbrev = "sant_2", name = "Selenopemphix antarctica sp2") 

# manual addition from Marret
taxons_marret <- c(
  `Achomosphaera andalousiense` = "aand",
  `Caspidinium rugosum` = "crug",
  `Impagidinium caspienense` = "icas",
  `Impagidinium japonicum` = "ijap",
  `Lingulodinium machaerophorum` = "lmac",
  `Melitasphaeridium choanophorum` = "Mcho",
  `Nematosphaeropsis rigida` = "nrig",
  `Operculodinium aguinawense` = "oagu",
  `Operculodinium giganteum` = "ogig",
  `Spiniferites cruciformis` = "scru",
  `Spiniferites elongatus` = "selo", 
  `Spiniferites bentorii` = "sben",
  `Spiniferites sp. granular type` = "sgra",
  `Scrippsiella trifida` = "stri",
  `Echinidinium karaense` =  "ekar",
  `Trinovantedinium variabile` = "tvar",
  `Polykrikos sp. arctic morphotype` = "parc",
  `Polykrikos hartmannii` = "phar",
  `Echinidinium zonneveldiae` = "ezon",
  `Stelladinium bifurcatum` = "sbif",
  `Tuberculodinium vancampoae` = "tvan",
  `Biecheleria baltica` = "bbal",
  `Peridinium ponticum` = "ppon",
  `Protoperidinium monospinum` = "pmon",
  `Echinidinium bispiniformum` = "ebis",
  `Oblea acanthocysta` = "oaca",
  `Trinovantedinium pallidifulvum` = "tpal",
  `Protoperidium minutum` = "pmin",
  `Melitasphaeridium choanophorum` = "mcho"
)
taxon_nms <- append(
  setNames(taxons_thole$name, nm = taxons_thole$abbrev), 
  setNames(names(taxons_marret), taxons_marret)
  )

# recode taxons
dino_nms <- dplyr::mutate(
  dino_nms,  
  species = dplyr::recode(.data$species, !!!taxon_nms)
  ) |> 
  tidyr::separate(
    species, 
    sep = " ", 
    into = c("genus", "species", "add"),  
    extra = "merge", 
    fill = "right"
    ) |> 
   tidyr::separate(
    add, 
    sep = "sensu", 
    into = c("subspecies", "species_author"),
    extra = "merge", 
    fill = "right"
    ) |> 
  dplyr::mutate(
    species = 
      dplyr::if_else(
        stringr::str_detect(.data$species, "^spp|^sp"), 
        NA_character_, 
        .data$species
        )
    )

# write table to DB (NSB neptune_taxonomy)
DBI::dbWriteTable(con, "neptune_taxonomy", dino_nms, overwrite = TRUE)
```


Useful sources working with SQLite and DBconnect

- https://www.datacamp.com/community/tutorials/beginners-guide-to-sqlite
- https://db.rstudio.com/databases/sqlite/
- https://db.rstudio.com/getting-started/database-queries/